### PR TITLE
Improve code coverage

### PR DESCRIPTION
**Pull request by MingshiPeng**
Code coverage improved to 90%.

### CODE REVIEW

**Comment by majia67** [comment]
Could you also add codecov integration in our repository to automatically show the code coverage info?

**Comment by MingshiPeng** [comment]
Hi @majia67 , the initialize_logging() part in server.py was not covered by tests earlier, by uncommenting the code in setUpClass() in test_server.py, the initialize_logging() was covered in the test and thus the coverage was improved to 90%. I guess the reason why the coverage dropped to 86% is that new code that wasn't fully covered was checked in after this PR was created.

**Comment by MingshiPeng** [comment]
Hi @majia67 , after merging with the latest code from master and running nosetests, I got 89% coverage in server.py and 91% in total. You may need to pull this branch to your local to see the coverage change.

**Comment by MingshiPeng** [comment]
Removed error handler for 405 & 500 since they were never used (it seems redundant to write tests for code that was never used anyway). Tests for root url was added.

Coverage: models.py - 93%, server.py - 94%.

**Pull request merged**
